config/routes.rb
Skynet::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :submissions, only: [:show, :new, :create, :destroy]
  post "submissions/:id/vote", to: "submissions#vote", method: :post, as: "submission_vote"

  resources :dashboard, only: [:index]

  get "personal/:user_id", to: "personal#show", as: "personal"
  get "nearby", to: "nearby#index", as: "nearby_index"
  get "nearby/nearby", to: "nearby#nearby"

  root "submissions#new"
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  self.per_page = 10
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :votes

  def can_delete?(u)
    !u.nil? && (u == self.user || u.admin?)
  end

  def self.nearby(lat, long, miles)
    find_by_sql ["SELECT *, 
          SQRT(
            POW(69.1 * (latitude - ?), 2) +
            POW(69.1 * (? - longitude) * COS(latitude / 57.3), 2)) AS distance
        FROM #{table_name} GROUP BY id HAVING (
          SQRT(
            POW(69.1 * (latitude - ?), 2) +
            POW(69.1 * (? - longitude) * COS(latitude / 57.3), 2))
        )< ? ORDER BY distance ASC LIMIT 20", lat, long, lat, long, miles]
  end
end

app/models/user.rb
# I used this page to help set this up: http://sreeharikmarar.blogspot.com/2013/01/omniauth-devise-authentication-using.html
class User < ActiveRecord::Base
  has_many :submissions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        Rails.logger.info auth.inspect
        Rails.logger.info auth.extra.inspect
        Rails.logger.info auth.extra.raw_info.inspect
        Rails.logger.info auth.extra.raw_info.name
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20]
                          )
      end
       
    end
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.info.name,
          provider:auth.provider,
          uid:auth.uid,
          email:auth.uid+"@twitter.com",
          password:Devise.friendly_token[0,20]
        )
      end
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :submission

  validates :user, :submission, :value, presence: true
  validates :value, inclusion: { in: [-1, 0, 1] }
  validates :submission_id, uniqueness: { scope: :user_id }

  scope :for_user, ->(user) do
    where(user: user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :store_return_to

  def redirect_back_or_default(default=nil)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_return_to
    session[:return_to] = request.fullpath
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @submissions = Submission
      .where("photo is not null")
      .order(created_at: :desc)
      .page(params[:page])
  end
end

app/controllers/nearby_controller.rb
class NearbyController < ApplicationController
  def index
  end

  def nearby
    @submissions = Submission.nearby(params[:latitude], params[:longitude], 2)
    render partial: 'nearby', locals: { submissions: @submissions }, layout: false
  end
end

app/controllers/personal_controller.rb
class PersonalController < ApplicationController
  def show
    @submissions = Submission
      .where(user_id: params[:user_id])
      .where("photo is not null")
      .order(created_at: :desc)
      .paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def show
    logger.info params.inspect
    @submission = Submission.find(params[:id])
  end

  def new
  end

  def create
    attributes = submission_params
    attributes[:photo] = uploaded_picture(attributes[:photo])
    @submission = Submission.new(attributes) do |s|
      s.user = current_user
    end
    if @submission.save
      redirect_to submission_path(@submission)
    else
      render :new
    end
  end

  def destroy
    submission = Submission.find(params[:id])
    if signed_in?
      submission.destroy if submission.can_delete?(current_user)
    end
    redirect_back_or_default
  end

  def vote
    submission = Submission.find(params[:id])
    if signed_in?
      value = params[:value].to_i
      Submission.transaction do
        submission.votes.build do |vote|
          vote.submission = submission
          vote.user = current_user
          vote.value = value
        end
        logger.info "HI"
        logger.info submission.inspect
        logger.info submission.votes.inspect
        logger.info submission.votes.first.valid?
        logger.info submission.votes.first.errors.inspect
        submission.vote_total += value
        submission.save!
      end
    end
    redirect_back_or_default submission_path(submission)
  end

  private

  def submission_params
    params.require(:submission).permit(:latitude, :longitude, :blue_factor, :photo)
  end

  def uploaded_picture(picture)
    return unless picture
    tempfile = Tempfile.new ['upload', 'jpg']
    tempfile.binmode
    tempfile.write(Base64.decode64(picture.sub("data:image/jpeg;base64,", "")))
    ActionDispatch::Http::UploadedFile.new(tempfile: tempfile, filename: 'upload.jpg')
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    auth = env["omniauth.auth"]
    #Rails.logger.info("auth is **************** #{auth.to_yaml}")
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/nearby_helper.rb
module NearbyHelper
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <%= will_paginate @submissions %>
  <div class="dashboard-photos clearfix">
    <% @submissions.each do |submission| %>
      <div class="dashboard-photo blue-factor-<%= submission.blue_factor %>">
        <a href="<%= submission_path(submission) %>">
        <%= image_tag submission.photo, class: "img-rounded", style: "height: 200px;" %>
        </a>
        <% if submission.can_delete?(current_user) %>
        <p class="text-center"><%= link_to "Delete", submission_path(submission), data: { confirm: "Are you sure?" }, class: "link-delete-submission", method: :delete, remote: true %></p>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= will_paginate @submissions %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skynet</title>

  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <link rel="shortcut icon" href="<%= asset_path("favicon.ico") %>" type="image/x-icon">
  <link rel="icon" href="<%= asset_path("favicon.ico") %>" type="image/x-icon">
  <link rel="icon" sizes="196x196" href="<%= asset_path("icon-196.png") %>">
  <link rel="icon" sizes="128x128" href="<%= asset_path("icon-128.png") %>">
  <link rel="apple-touch-icon" href="<%= asset_path("icon-196.png") %>" />
  <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path("icon-76.png") %>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path("icon-128.png") %>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path("icon-152.png") %>">
  <link rel="apple-touch-icon-precomposed" href="<%= asset_path("icon-196.png") %>" />
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="<%= asset_path("icon-76.png") %>">
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="<%= asset_path("icon-128.png") %>">
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="<%= asset_path("icon-152.png") %>">

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<div>

<div class="title row no-margin">
  <div class="col-xs-2 text-center">
    <a href="#left-menu"><h3 class="fa fa-bars"></h3></a>
  </div>
  <div class="col-xs-8 text-center">
    <h1><%= link_to "SKYNET", root_path %></h1>
  </div>
</div>

<div class="row no-margin header-row">
  <div class="col-xs-2 header-bar blue-factor-0"></div>
  <div class="col-xs-2 header-bar blue-factor-1"></div>
  <div class="col-xs-2 header-bar blue-factor-2"></div>
  <div class="col-xs-2 header-bar blue-factor-3"></div>
  <div class="col-xs-2 header-bar blue-factor-4"></div>
  <div class="col-xs-2 header-bar blue-factor-5"></div>
</div>

<nav id="left-menu">
  <ul>
    <% if signed_in? %>
      <li class="Label"><%= current_user.name %><li>
    <% end %>

    <li>
      <a href="<%= root_path %>">
        <span class="fa fa-home"></span>Home
      </a>
    </li>

    <% if !signed_in? %>
      <li class="Label">Log in using<li>
      <li>
        <a href="<%= user_omniauth_authorize_path(:facebook) %>">
          <span class="fa fa-facebook"></span>Facebook
        </a>
      <li>
        <a href="<%= user_omniauth_authorize_path(:twitter) %>">
          <span class="fa fa-twitter"></span>Twitter
        </a>
      </li>
    <% end %>

    <% if signed_in? %>
      <% if current_user.admin? %>
        <li>
          <a href="<%= dashboard_index_path %>">
            <span class="fa fa-th"></span>Dashboard
          </a>
        </li>
      <% end %>
      <li>
        <a href="<%= personal_path(current_user) %>">
          <span class="fa fa-dot-circle-o"></span>My Photos
        </a>
      </li>
      <li>
        <a href="<%= destroy_user_session_path %>" rel="nofollow" data-method="delete">
          <span class="fa fa-circle-o"></span>Log Out
        </a>
      </li>
    <% end %>
  </ul>
</nav>

<%= yield %>

</div>

</body>
</html>

app/views/nearby/_nearby.html.erb
<div class="container">
  <% if submissions.empty? %>
    <div class="text-center nearby-empty">
      <p>No photos have been submitted near you. Submit one!</p>
    </div>
  <% else %>
    <% submissions.each do |submission| %>
      <div class="personal-photo blue-factor-<%= submission.blue_factor %> text-center">
        <a href="<%= submission_path(submission) %>">
        <%= image_tag submission.photo, class: "img-responsive" %>
        </a>
      </div>
    <% end %>
  <% end %>
</div>

app/views/nearby/index.html.erb
<div id="nearby-index"></div>

<div id="nearby-content"></div>

app/views/personal/show.html.erb
<div class="container">
  <%= will_paginate @submissions %>
  <% @submissions.each do |submission| %>
    <div class="personal-photo blue-factor-<%= submission.blue_factor %> text-center">
      <a href="<%= submission_path(submission) %>">
      <%= image_tag submission.photo, class: "img-responsive" %>
      </a>
    </div>
  <% end %>
  <%= will_paginate @submissions %>
</div>

app/views/submissions/new.html.erb
<span id="submissions-new"></span>

<%= form_for :submission, url: submissions_path, html: { id: "submission-form" } do |f| %>

  <div id="initial-container">
    <h2>Contribute to air quality analysis using only your phone.</h2>
    <div id="intro-container">
      <div class="row no-margin">
        <div class="col-xs-4 left">
          <strong>1</strong>
          <p>Take a photo of the sky.</p>
        </div>
        <div class="col-xs-4 middle">
          <strong>2</strong>
          <p>Tap the best color match.</p>
        </div>
        <div class="col-xs-4 right">
          <strong>3</strong>
          <p>Submit to see results.</p>
        </div>
      </div>
    </div>
  </div>
  <div id="picture-container">
    <img id="show-picture" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs%3D" class="img-responsive center-block uploaded-photo"></img>

    <div class="row no-margin">
      <div id="palette-color-0" class="palette-color col-xs-4 text-center" data-palette-index="0">
        <h2 class="palette-check glyphicon glyphicon-ok-circle"></h2>
        <!--<div class="distance"></div>-->
      </div>
      <div id="palette-color-1" class="palette-color col-xs-4 text-center" data-palette-index="1">
        <h2 class="palette-check glyphicon glyphicon-ok-circle"></h2>
        <!--<div class="distance"></div>-->
      </div>
      <div id="palette-color-2" class="palette-color col-xs-4 text-center" data-palette-index="2">
        <h2 class="palette-check glyphicon glyphicon-ok-circle"></h2>
        <!--<div class="distance"></div>-->
      </div>
    </div>
  </div>


  <%= f.hidden_field :latitude, id: "submission-latitude" %>
  <%= f.hidden_field :longitude, id: "submission-longitude" %>
  <%= f.hidden_field :blue_factor, id: "submission-blue-factor" %>
  <%= f.hidden_field :photo, id: "upload-image-data" %>

  <div class="footer">
    <div class="container row no-margin submit-row">
      <div class="col-xs-offset-2 col-xs-6">
        <div id="step-1" class="step pull-right">
          Shoot the sky.
        </div>
        <div id="step-2" class="step pull-right">
          Match sky color.
        </div>
        <div id="step-3" class="step pull-right">
          Send your results.
        </div>
      </div>
      <div class="col-xs-4 text-center">
        <div id="camera-container">
          <span class="btn btn-default btn-file btn-lower-right">
            <input type="file" id="take-picture" accept="image/*" capture="camera"></input>
            <h2 class="glyphicon glyphicon-camera"></h2>
          </span>
        </div>
        <div id="submit-container">
          <button id="submit-button" type="submit" class="btn btn-default btn-lower-right">
            <h2 class="glyphicon glyphicon-share-alt"></h2>
          </button>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/submissions/show.html.erb
<span id="submissions-show"></span>

<span id="submission"
  data-blue-factor="<%= @submission.blue_factor %>"
  ></span>

<div id="show-container">

  <div class="show-submission">
    <%= image_tag @submission.photo, class: "center-block uploaded-photo" %>
  </div>

  <div class="text-center photo-summary-hero blue-color-<%= @submission.blue_factor %>">
    <h2>BEAUTIFUL SKY</h2>
  </div>

  <div class="photo-summary-whole" >
    <div class="row no-margin photo-summary">
      <div class="col-xs-4 border-right">
        <p class="photo-summary-left">Blue</p>
      </div>
      <div class="col-xs-4 border-right">
        <p class="photo-summary-middle">Clear</p>
      </div>
      <div class="col-xs-4">
        <p class="photo-summary-right">Low Aerosol</p>
      </div>
    </div>
    <div class="row no-margin photo-summary">
      <div class="col-xs-4 border-right">
        <h4>Color</h4>
      </div>
      <div class="col-xs-4 border-right">
        <h4>Visibility</h4>
      </div>
      <div class="col-xs-4">
        <h4>Aerosol</h4>
      </div>
    </div>
  </div>

  <%# link_to "vote up", submission_vote_path(@submission, value: 1), method: :post %>
  <%# link_to "vote down", submission_vote_path(@submission, value: -1), method: :post %>

</div>